server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: contract-management-api
    static_configs:
      - targets:
          - localhost
        labels:
          job: contract-api
          service: contract-management-api
          __path__: /var/log/app/*.log
    
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            request_id: request_id
            duration_ms: duration_ms
            status_code: status_code
            method: method
            endpoint: endpoint
      
      - labels:
          level:
          method:
      
      - timestamp:
          source: timestamp
          format: Unix
      
      - output:
          source: message
