"""Add activity history table

Revision ID: 35df130d2b97
Revises: c61521afcb64
Create Date: 2025-10-10 08:52:30.800603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35df130d2b97'
down_revision = 'c61521afcb64'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_instance_id', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('user', sa.String(length=100), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_instance_id'], ['contracts.contract_instance_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_history')
    # ### end Alembic commands ###
