"""add_description_to_contracts

Revision ID: c61521afcb64
Revises: f981f1f0e4c1
Create Date: 2025-10-09 06:10:58.010175+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c61521afcb64'
down_revision = 'f981f1f0e4c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'description')
    # ### end Alembic commands ###
