"""add_renewal_tracking_fields

Revision ID: f981f1f0e4c1
Revises: 9a772365714e
Create Date: 2025-10-09 03:53:45.030367+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f981f1f0e4c1'
down_revision = '9a772365714e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('renewed_from', sa.String(length=100), nullable=True))
    op.add_column('contracts', sa.Column('renewed_to', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'renewed_to')
    op.drop_column('contracts', 'renewed_from')
    # ### end Alembic commands ###
